version: "3"

services:
    app:
        restart: always
        container_name: app-server
        hostname: app-server
        build: ./app
        volumes:
            - "./app:/var/www/"
        environment:
            TZ: Asia/Tokyo
    web:
        restart: always
        container_name: web-server
        hostname: web-server
        build: ./web
        volumes:
            - "./web/nginx.conf:/etc/nginx/nginx.conf"
            - "/tmp/nginx_log:/var/log/nginx"
        ports:
            - "30010:80"
        environment:
            TZ: Asia/Tokyo
